## Basic Configuration
baseurl = "https://miguelace.com/"
languageCode = "en"

title = "Miguel Acevedo"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Author"
    title = "Miguel Acevedo"
    # description = "..."
    authorimage = "/miguel.jpeg"
    dateformat = "Jan 2, 2006"
    mainSections = ["portfolio", "posts"]

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "miguel-acevedo"
    linkedin = "miguel-acevedo-171207133"
    twitter = "miglets80"
    email = "mhacevedo@ucdavis.edu"
    # gravatar = "mhacevedo@ucdavis.edu"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
#[[menu.main]]
#    name = "About"
#    identifier = "about"
#    weight = 300
#    url = "/about/"

# sidebar color: #1b1b1b
# background-color: #fdfdfd